### PR TITLE
fix deinit generation and optional protocol methonds

### PR DESCRIPTION
**Pull request by mrgerych**

### CODE REVIEW

**Comment by TadeasKriz** [comment]
@mrgerych Hey, thanks for the PR! I'll review it today, but in order to merge it, I'll need you to force-push only your commit to this branch in order to remove the merge commits from other PRs. Could you do that? Thanks.

**Comment by mrgerych** [comment]
Will do it.

**Comment by TadeasKriz** [comment]
Could you also rebase it on top of current master? Thanks.

**Comment by mrgerych** [comment]
made it with another PR

**Pull request closed without merging**
